apiVersion: v1
kind: Service
metadata:
  name: okta-service
spec:
  type: NodePort
  selector:
    app: fork-okta-spring-boot-sample
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
